### ISSUE TITLE
Copyright 

### ISSUE THREAD

**Issue by ashaqhussain** [SagaMusic/saga-android#5]
Are you sure it is legal to download music from Youtube.
If yes, i will be more than glad to know how?

**Comment by AnandChowdhary** [comment]
This app was made as an educational experiment. It's against YouTube's Terms of Service to download music as MP3. This app uses YouTubeMP3, a third-party service that converts YouTube videos to MP3 files, and RhythmSaga, a free and legal music tagging and metadata API that I made.
